(function () {
    "use strict";

    var SE_TYPES = {
        ACTION_LOG_TYPE: {
            N2S: {
                0: "AGENT_SETTING",
                1: "AGENT_PROPERTY",
                2: "AGENT_CREATE",
                3: "AGENT_DELETE",
                4: "AGENT_GENERIC",
                22: "AGENT_TAG_ADD",
                23: "AGENT_TAG_REMOVE",
                100: "CONTAINER_SETTING",
                101: "CONTAINER_PROPERTY",
                102: "CONTAINER_CREATE",
                103: "CONTAINER_DELETE",
                104: "CONTAINER_GENERIC",
                105: "CONTAINER_INVENTORY",
                106: "CONTAINER_REMOTEACCESS",
                107: "CONTAINER_REMOTEACCESSPERFORMED",
                108: "CONTAINER_POWERSHELLACCESS",
                109: "CONTAINER_POWERSHELLACCESSPERFORMED",
                110: "CONTAINER_SYSTEMSHUTDOWN",
                122: "CONTAINER_TAG_ADD",
                123: "CONTAINER_TAG_REMOVE",
                202: "NOTE_CREATE",
                203: "NOTE_DELETE",
                300: "NOTIFY_SETTING",
                302: "NOTIFY_CREATE",
                303: "NOTIFY_DELETE",
                310: "NOTIFY_SENT_OK",
                311: "NOTIFY_SENT_ERROR",
                402: "REPORT_CREATE",
                403: "REPORT_DELETE",
                410: "REPORT_TEMPLATE_CHANGE",
                412: "REPORT_TEMPLATE_CREATE",
                413: "REPORT_TEMPLATE_DELETE",
                502: "USER_TWOFACTOR_ENABLE",
                503: "USER_TWOFACTOR_DISABLE",
                600: "COMPLIANCE_CONFIG_CHANGE",
                602: "COMPLIANCE_CONFIG_CREATE",
                603: "COMPLIANCE_CONFIG_DELETE",
                700: "TAG_CHANGE",
                702: "TAG_CREATE",
                703: "TAG_DELETE",
                800: "PM_CONFIG_CHANGE",
                802: "PM_CONFIG_CREATE",
                803: "PM_CONFIG_DELETE",
                900: "VAULT_CREATE",
                901: "VAULT_UPDATE",
                902: "VAULT_DELETE",
                903: "VAULT_RESTORE",
                904: "VAULT_ENTRY_CREATE",
                905: "VAULT_ENTRY_UPDATE",
                906: "VAULT_ENTRY_DELETE",
                907: "VAULT_USER_CREATE",
                908: "VAULT_USER_UPDATE",
                909: "VAULT_USER_DELETE",
                1000: "POWERSHELL_REPOSITORY_CREATE",
                1001: "POWERSHELL_REPOSITORY_UPDATE",
                1002: "POWERSHELL_REPOSITORY_DELETE",
                1003: "POWERSHELL_REPOSITORY_SCRIPT_CREATE",
                1004: "POWERSHELL_REPOSITORY_SCRIPT_UPDATE",
                1005: "POWERSHELL_REPOSITORY_SCRIPT_DELETE",
                1006: "POWERSHELL_REPOSITORY_USER_CREATE",
                1007: "POWERSHELL_REPOSITORY_USER_UPDATE",
                1008: "POWERSHELL_REPOSITORY_USER_DELETE",
                1100: "RMM_SESSION_CREATE",
                1102: "RMM_SESSION_DELETE",
                1200: "SCHEDULED_TASK_CREATE",
                1201: "SCHEDULED_TASK_UPDATE",
                1202: "SCHEDULED_TASK_DELETE",
                1203: "SCHEDULED_TASK_TRIGGER_CREATE",
                1204: "SCHEDULED_TASK_TRIGGER_UPDATE",
                1205: "SCHEDULED_TASK_TRIGGER_DELETE",
            },
            S2N: {
                AGENT_SETTING: 0,
                AGENT_PROPERTY: 1,
                AGENT_CREATE: 2,
                AGENT_DELETE: 3,
                AGENT_GENERIC: 4,
                AGENT_TAG_ADD: 22,
                AGENT_TAG_REMOVE: 23,
                CONTAINER_SETTING: 100,
                CONTAINER_PROPERTY: 101,
                CONTAINER_CREATE: 102,
                CONTAINER_DELETE: 103,
                CONTAINER_GENERIC: 104,
                CONTAINER_INVENTORY: 105,
                CONTAINER_REMOTEACCESS: 106,
                CONTAINER_REMOTEACCESSPERFORMED: 107,
                CONTAINER_POWERSHELLACCESS: 108,
                CONTAINER_POWERSHELLACCESSPERFORMED: 109,
                CONTAINER_SYSTEMSHUTDOWN: 110,
                CONTAINER_TAG_ADD: 122,
                CONTAINER_TAG_REMOVE: 123,
                NOTE_CREATE: 202,
                NOTE_DELETE: 203,
                NOTIFY_SETTING: 300,
                NOTIFY_CREATE: 302,
                NOTIFY_DELETE: 303,
                NOTIFY_SENT_OK: 310,
                NOTIFY_SENT_ERROR: 311,
                REPORT_CREATE: 402,
                REPORT_DELETE: 403,
                REPORT_TEMPLATE_CHANGE: 410,
                REPORT_TEMPLATE_CREATE: 412,
                REPORT_TEMPLATE_DELETE: 413,
                USER_TWOFACTOR_ENABLE: 502,
                USER_TWOFACTOR_DISABLE: 503,
                COMPLIANCE_CONFIG_CHANGE: 600,
                COMPLIANCE_CONFIG_CREATE: 602,
                COMPLIANCE_CONFIG_DELETE: 603,
                TAG_CHANGE: 700,
                TAG_CREATE: 702,
                TAG_DELETE: 703,
                PM_CONFIG_CHANGE: 800,
                PM_CONFIG_CREATE: 802,
                PM_CONFIG_DELETE: 803,
                VAULT_CREATE: 900,
                VAULT_UPDATE: 901,
                VAULT_DELETE: 902,
                VAULT_RESTORE: 903,
                VAULT_ENTRY_CREATE: 904,
                VAULT_ENTRY_UPDATE: 905,
                VAULT_ENTRY_DELETE: 906,
                VAULT_USER_CREATE: 907,
                VAULT_USER_UPDATE: 908,
                VAULT_USER_DELETE: 909,
                POWERSHELL_REPOSITORY_CREATE: 1000,
                POWERSHELL_REPOSITORY_UPDATE: 1001,
                POWERSHELL_REPOSITORY_DELETE: 1002,
                POWERSHELL_REPOSITORY_SCRIPT_CREATE: 1003,
                POWERSHELL_REPOSITORY_SCRIPT_UPDATE: 1004,
                POWERSHELL_REPOSITORY_SCRIPT_DELETE: 1005,
                POWERSHELL_REPOSITORY_USER_CREATE: 1006,
                POWERSHELL_REPOSITORY_USER_UPDATE: 1007,
                POWERSHELL_REPOSITORY_USER_DELETE: 1008,
                RMM_SESSION_CREATE: 1100,
                RMM_SESSION_DELETE: 1102,
                SCHEDULED_TASK_CREATE: 1200,
                SCHEDULED_TASK_UPDATE: 1201,
                SCHEDULED_TASK_DELETE: 1202,
                SCHEDULED_TASK_TRIGGER_CREATE: 1203,
                SCHEDULED_TASK_TRIGGER_UPDATE: 1204,
                SCHEDULED_TASK_TRIGGER_DELETE: 1205
            },
        },
        AGENT_INCARNATION: {
            N2S: {
                0: "AGENT",
                1: "SHADOW",
                2: "DENIED_SHADOW",
                3: "TEMPLATE",
                4: "EXTERNAL",
            },
            S2N: {
                "AGENT": 0,
                "SHADOW": 1,
                "DENIED_SHADOW": 2,
                "TEMPLATE": 3,
                "EXTERNAL": 4,
            },
        },
        APIKEY_TYPE: {
            N2S: {
                0: "USER",
                1: "CUSTOMER",
                2: "CONTAINER",
            },
            S2N: {
                "USER": 0,
                "CUSTOMER": 1,
                "CONTAINER": 2,
            },
        },
        CONTAINER_TYPE: {
            N2S: {
                0: "MAC",
                1: "SECMAC",
                2: "CAC",
                3: "TEMPLATE",
                4: "EXTERNAL",
            },
            S2N: {
                "MAC": 0,
                "SECMAC": 1,
                "CAC": 2,
                "TEMPLATE": 3,
                "EXTERNAL": 4,
            },
        },
        INTERNAL_EVENT: {
            N2S: {
                0: "USER_CHANGE",
                1: "NODE_ADD",
                2: "NODE_UPDATE",
                3: "NODE_REMOVE",
                4: "REMOTE_RESULT",
            },
            S2N: {
                "USER_CHANGE": 0,
                "NODE_ADD": 1,
                "NODE_UPDATE": 2,
                "NODE_REMOVE": 3,
                "REMOTE_RESULT": 4,
            },
        },
        LICENSE_TYPE: {
            N2S: {
                0: "DEACTIVATED",
                1: "DEMO",
                2: "FREEWARE",
                3: "FULL",
            },
            S2N: {
                "DEACTIVATED": 0,
                "DEMO": 1,
                "FREEWARE": 2,
                "FULL": 3,
            },
        },
        NODE_STATUS: {
            N2S: {
                0: "NOT_INITIALIZED",
                1: "SHUTDOWN",
                2: "OK",
                3: "ERROR",
                4: "NO_HEARTBEAT",
                5: "INHERIT",
                6: "WORKING",
            },
            S2N: {
                "NOT_INITIALIZED": 0,
                "SHUTDOWN": 1,
                "OK": 2,
                "ERROR": 3,
                "NO_HEARTBEAT": 4,
                "INHERIT": 5,
                "WORKING": 6,
            },
        },
        NODE_TYPE: {
            N2S: {
                0: "USER",
                1: "CUSTOMER",
                2: "CONTAINER",
                3: "AGENT",
                4: "TEMPLATES",
                5: "TEMPLATE",
                6: "TEMPLATEAGENT",
                7: "CUSTOMERS",
                8: "EXTERNALS",
                9: "EXTERNAL_CONTAINER",
                10: "EXTERNAL_AGENT",
                11: "REPORT",
                12: "REPORT_TEMPLATE",
                13: "COMPLIANCE_CONFIG",
                14: "PM_CONFIG",
                15: "VAULT",
                16: "POWERSHELL_REPOSITORY",
                17: "SCHEDULED_TASK",
            },
            S2N: {
                "USER": 0,
                "CUSTOMER": 1,
                "CONTAINER": 2,
                "AGENT": 3,
                "TEMPLATES": 4,
                "TEMPLATE": 5,
                "TEMPLATEAGENT": 6,
                "CUSTOMERS": 7,
                "EXTERNALS": 8,
                "EXTERNAL_CONTAINER": 9,
                "EXTERNAL_AGENT": 10,
                "REPORT": 11,
                "REPORT_TEMPLATE": 12,
                "COMPLIANCE_CONFIG": 13,
                "PM_CONFIG": 14,
                "VAULT": 15,
                "POWERSHELL_REPOSITORY": 16,
                "SCHEDULED_TASK": 17,
            },
        },
        PUSH_CONTROL: {
            N2S: {
                0: 'ADD_OR_UPDATE_AGENT',
                1: 'DELETE_AGENT',
                2: 'REFRESH_AGENT',
                3: 'UPDATE_CONTAINER',
                4: 'RESTART_CONTAINER',
                5: 'REMOTE_DRIVE',
                6: 'REMOTE_SERVICE',
                7: 'REMOTE_PROCESS',
                8: 'REMOTE_INFORMATION',
                9: 'REMOTE_ACTION',
                10: 'CUSTOM_ACTION',
                11: 'REMOTE_INSTALL',
                12: 'REMOTE_INSTALL2',
                13: 'REMOTE_ACTIVE_DIRECTORY',
                14: 'SHUTDOWN_CONTAINER',
                15: 'REFRESH_ONLINE_PROPERTIES',
                16: 'ADD_OR_UPDATE_TASKS',
            },
            S2N: {
                'ADD_OR_UPDATE_AGENT': 0,
                'DELETE_AGENT': 1,
                'REFRESH_AGENT': 2,
                'UPDATE_CONTAINER': 3,
                'RESTART_CONTAINER': 4,
                'REMOTE_DRIVE': 5,
                'REMOTE_SERVICE': 6,
                'REMOTE_PROCESS': 7,
                'REMOTE_INFORMATION': 8,
                'REMOTE_ACTION': 9,
                'CUSTOM_ACTION': 10,
                'REMOTE_INSTALL': 11,
                'REMOTE_INSTALL2': 12,
                'REMOTE_ACTIVE_DIRECTORY': 13,
                'SHUTDOWN_CONTAINER': 14,
                'REFRESH_ONLINE_PROPERTIES': 15,
                'ADD_OR_UPDATE_TASKS': 16,
            },
        },
        LOGNOTE_TYPE: {
            N2S: {
                0: "WORKING",
                1: "REOPEN",
                2: "FALSE_ALERT",
                3: "HINT",
                4: "CHANGE",
            },
            S2N: {
                "WORKING": 0,
                "REOPEN": 1,
                "FALSE_ALERT": 2,
                "HINT": 3,
                "CHANGE": 4,
            },
        },
        USER_ROLE: {
            N2S: {
                0: "ADMIN",
                1: "USER",
                2: "LEAD",
                3: 'INSTALLER',
                4: 'ARCHITECT',
                5: 'TECHIE',
                6: 'HINTER',
                7: 'HR',
                8: 'REPORTING',
                9: 'MAV',
                10: 'PM',
                11: 'PCVISIT',
                12: 'POWERSHELL',
                13: 'TANSS',
                14: 'RMM',
                15: 'TASKS',
            },
            S2N: {
                ADMIN: 0,
                USER: 1,
                LEAD: 2,
                INSTALLER: 3,
                ARCHITECT: 4,
                TECHIE: 5,
                HINTER: 6,
                HR: 7,
                REPORTING: 8,
                MAV: 9,
                PM: 10,
                PCVISIT: 11,
                POWERSHELL: 12,
                TANSS: 13,
                RMM: 14,
                TASKS: 15,
            },
        },
    }

    angular.module('ngSeApi').factory('SeaTypes', [
        function () {
            return SE_TYPES;
        }]);
})();